export namespace JWT {
  export const JWT_SECRET_NOT_FOUND = 'JWT_SECRET_NOT_FOUND';
  export const JWT_INVALID_TOKEN = 'JWT_INVALID_TOKEN';
  export const JWT_EXPIRES_TIME_FOUND = 'JWT_EXPIRES_TIME_FOUND';
}

export type TYPE_JWT_SECRET_NOT_FOUND = typeof JWT.JWT_SECRET_NOT_FOUND;
export type TYPE_JWT_INVALID_TOKEN = typeof JWT.JWT_INVALID_TOKEN;
export type TYPE_JWT_EXPIRES_TIME_FOUND = typeof JWT.JWT_EXPIRES_TIME_FOUND;
